version: "{build}"

clone_depth: 100

environment:
  matrix:
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # We need wheel installed to build wheels
  - "python.exe -m pip install wheel"
  - "python.exe -m pip install codecov"
  - "python.exe -m pip install -r requirements.txt"
  - "python.exe -m pip install -r requirements-test.txt"

build: off

test_script:
  - "py.test --cov=wlc"

after_test:
  - "codecov"
  - "python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
